### ISSUE TITLE
When opening the preview window on an image, MODX logs some errors

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#28] opened 2021-11-09 11:09 UTC
```
[2021-11-09 12:08:47] (WARN @ /var/www/html/cms/core/components/mediamanager/model/mediamanager/classes/files.class.php : 282) PHP notice: Undefined index: categories
[2021-11-09 12:08:47] (WARN @ /var/www/html/cms/core/components/mediamanager/model/mediamanager/classes/files.class.php : 292) PHP notice: Undefined index: tags

```

The selected images does have a category and a tag.

**Comment by sonicpunk** [comment] 2021-11-23 08:22
After testing 0.2.5. These errors still exist for us.

**Comment by sdrenth** [comment] 2022-05-05 13:08
@sonicpunk I'm unable to reproduce this, can you confirm this issue has been resolved now?

I checked using version 0.2.9

**Comment by sdrenth** [comment] 2022-05-06 07:34
@sonicpunk I reproduced this error now with a newer PHP version.

**Comment by sonicpunk** [comment] 2022-05-06 07:41
@sdrenth We are running PHP 7.4

**Comment by sdrenth** [comment] 2022-05-06 09:50
@sonicpunk These warnings have been fixed and will be included in the upcoming release. Thank you for bringing this to our attention.

**Closed as completed by sdrenth** 2022-05-06 09:50 UTC
